### ISSUE TITLE
are you still running the server?

### ISSUE THREAD

**Issue by taciturnaxolotl** [donovanhubbard/wizard-duel#3]
Hi! I wanted to try your game, so I tried to ssh into wizards.svenxix.net, but I couldn't connect; I ended up just trying it locally, but I was wondering if you had depreciated the server and aren't hosting it anymore or something

**Comment by taciturnaxolotl** [comment]
@donovanhubbard

**Comment by donovanhubbard** [comment]
No, I shut the server down as I didn't want to pay for hosting anymore. I removed that reference on the readme and included instructions on how to run it yourself.
